### ISSUE TITLE
BUILD FAILED

### ISSUE THREAD

**Issue by kamike** [royd/KotlinAppWithXamarinDependency#1]
![image](https://user-images.githubusercontent.com/3920019/43764826-141732c6-9a61-11e8-8ac8-745eaff78f4a.png)

java.io.IOException: Cannot run program "\Library\Frameworks\Mono.framework\Versions\Current\Commands\msbuild" (in directory "F:\git_project\XamarinDependency\XamarinDependency.Application"): CreateProcess error=2, 系统找不到指定的文件。

**Comment by gab0sz** [comment]
Hi!

I am facing the same problem. 
Could you tell how did you solve this or what could go wrong?
