### ISSUE TITLE
Question about Compilation Errors

### ISSUE THREAD

**Issue by masterwok** [royd/KotlinAppWithXamarinDependency#2]
Hi there,

I recently discovered your article about embedding C# into a native Android project and I'm trying to reproduce the outlined steps (excellent article by the way!). Unfortunately, I'm running into the following compilation errors during the `compileDebugJavaWithJavac` task:

```
/Users/jonathantrowbridge/Desktop/XamarinDependency/XamarinDependency/obj/Debug/android/src/com/masterwok/xamarindependency/Library/HelloXamarinService.java:7: error: cannot find symbol
		mono.android.IGCUserPeer,
		            ^
  symbol:   class IGCUserPeer
  location: package mono.android
/Users/jonathantrowbridge/Desktop/XamarinDependency/XamarinDependency/obj/Debug/android/src/mono/MonoRuntimeProvider.java:35: error: cannot find symbol
		mono.MonoPackageManager.LoadApplication (context, applicationInfo, apks);
		    ^
  symbol:   class MonoPackageManager
  location: package mono
/Users/jonathantrowbridge/Desktop/XamarinDependency/XamarinDependency/obj/Debug/android/src/com/masterwok/xamarindependency/Library/HelloXamarinService.java:16: error: cannot find symbol
		mono.android.Runtime.register ("XamarinDependnecy.Library.HelloXamarinService, XamarinDependnecy.Library", HelloXamarinService.class, __md_methods);
		            ^
  symbol:   class Runtime
  location: package mono.android
Note: /Users/jonathantrowbridge/Desktop/XamarinDependency/XamarinDependency/obj/Debug/android/src/com/masterwok/xamarindependency/Library/HelloXamarinService.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors

FAILURE: Build failed with an exception.
```

My initial though is that for whatever reason the `mono.andorid.jar` file was failing to resolve (which it was). I've since updated my `build.gradle` to point to the correct path but the issue still persists.

Do you have any insight on how I might be able to resolve this issue? Thanks!

**Comment by masterwok** [comment]
I've since included the `java_runtime.jar` and seem to be down to just one error:

```
e: Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class com.masterwok.xamarindependency.Library.HelloXamarinService, unresolved supertypes: mono.android.IGCUserPeer
```

**Comment by royd** [comment]
Adding `java_runtime.jar` fixed it for me. Perhaps a `./gradlew clean` would help? I'll push what I have.

**Comment by masterwok** [comment]
I was able to get the project to run on my physical device thanks to your changes! You are a lifesaver. This is the only resource I've found for doing something like this. Thank you!

**Comment by Volatile-Memory** [comment]
> I've since included the `java_runtime.jar` and seem to be down to just one error:
> 
> ```
> e: Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
>     class com.masterwok.xamarindependency.Library.HelloXamarinService, unresolved supertypes: mono.android.IGCUserPeer
> ```

I think I am running into this issue when I try to compile against Android 9 SDK.

I would like to compile against Android 10 because by the time our app ships, Google will start requiring that for our app to be accepted. I filed another bug on whats stopping me from compiling against Android 10, but in the meantime it would be nice to get at least Android 9 compilation to work. How did you fix this issue?
