### ISSUE TITLE
The reference assemblies for .NETFramework,Version=v10.0 were not found.

### ISSUE THREAD

**Issue by Volatile-Memory** [royd/KotlinAppWithXamarinDependency#6]
https://github.com/royd/KotlinAppWithXamarinDependency/blob/c9322a77348f9f8b49be1d219dc0711787fde0c4/xamarin/build.gradle#L118
https://github.com/royd/KotlinAppWithXamarinDependency/blob/c9322a77348f9f8b49be1d219dc0711787fde0c4/xamarin/build.gradle#L129

At the end of these two lines you added the following:

```groovy
"/property:TargetFrameworkVersion=$xamarinTargetFrameworkVersion"
```

which references 

```groovy
String xamarinTargetFrameworkVersion = "v10.0" // Corresponds to compileSdkVersion
```

but when I compile with that last flag I get the error in this issues title:

> 
> "/Users/v/dev/.../code.csproj" (default target) (5:2) ->
>   /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(1193,5): error MSB3644: The reference assemblies for .NETFramework,Version=v10.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [/Users/v/dev/sk/starkit/xamarin/hiaservicelibrary/HIAAsAService/ActivityTracker/ActivityTracker.csproj]
> 
>     15 Warning(s)
>     2 Error(s)
> 
> Time Elapsed 00:00:22.28

I think this is the incorrect flag.

removing this flag from the msbuild args yields the following error:

>   Microsoft.NuGet.targets(186, 5): Your project does not reference "MonoAndroid,Version=v10.0" framework. Add a reference to "MonoAndroid,Version=v10.0" in the "TargetFrameworks" property of your project file and then re-run NuGet restore.

I can't seem to figure out why this is the case, I have run NuGet Restore and confirmed that there is a dependency on MonoAndroid.

Oddly, Visual studio does seem to have a dependency with v0.0.0.0
![image](https://user-images.githubusercontent.com/2176942/103712049-6e4dd400-4f7e-11eb-98bd-d04d951cedf8.png)

**Comment by royd** [comment]
Could you paste the contents of your About Visual Studio information? Visual Studio -> About Visual Studio -> Show Details.

**Comment by royd** [comment]
Likely due to not having the development environment set up.

**Comment by Volatile-Memory** [comment]
Sorry for the delay. 

I was able to get  past this issue.

originally I had this in my .csproj:
```csharp
<Reference Include="Mono.Android" >
    <Private>True</Private>
</Reference>
```

When I changed it to omit Private like this
```csharp
    <Reference Include="Mono.Android" />
```

it was able to work.

that said, these
```
"/property:TargetFrameworkVersion=$xamarinTargetFrameworkVersion"
```
flags need to be removed in order to compile.
