### ISSUE TITLE
do a swiftAppWithDotnetDependency! u r so gr8t!

### ISSUE THREAD

**Issue by juepiezhongren** [royd/KotlinAppWithXamarinDependency#9]

**Comment by gsgou** [comment]
@royd  tks for this sample! Are you aware if this is also possible at all with Swift or Objective-C?

**Comment by royd** [comment]
This is possible for iOS. If I recall, it involves using Xamarin to generate bindings and compile into a static library, then link your Swift app against that and write the code that handles startup tasks such as registering types (very similar to the code for standard Xamarin app startup).

**Comment by gsgou** [comment]
Tks for your time to reply @royd . I will have a deeper look into it.
